spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.0.224:3306/sea_blog?useSSL=false&serverTimezone=Asia/Shanghai
    username: sea_blog
    password: sea12345678
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    password:
  # 其他开发环境配置

upload:
  local:
    url: http://localhost:9090/SEA-Blog/
    path: src/main/resources/
server:
  servlet:
    context-path: /SEA-Blog
  port: 9090
logging:
  level:
    org.apache.shiro: DEBUG