spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sea_blog?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决Swagger2 和 SpringBoot版本之间的冲突

server:
  servlet:
    context-path: /SEA-Blog
  port: 8080