spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678