name: syncToGitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          persist-credentials: false

      - name: Mirror to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/SEA-365'
          dst: 'gitee/SEA-365'
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "SEA-Blog"
