name: Sync to Gitee

on:
  push:
    branches:
      - main # github分支名

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Gitee
        run: |
          git remote add gitee git@gitee.com:sea-365/sea-blog.git
          git push --mirror gitee
        env:
          GIT_SSH_COMMAND: "ssh -i ${{ secrets.GITEE_TOKEN }}"
