name: syncToGitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Mirror to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/SEA-365'
          dst: 'gitee/SEA-365'
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "SEA-Blog"
